---
pull_request_rules:
  - name: Automatically approve Renovate PRs
    conditions:
      - author = renovate[bot]
      - check-success=Success
      - check-success=lint
    actions:
      review:
        type: APPROVE
