pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "branch-protection-review-decision=APPROVED"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - and: &CheckRuns
        - check-success~=lint
        - check-success~=test
    actions:
      merge:
        method: squash

  - name: automatic merge for Renovate pull requests after CI success
    conditions:
      - author=renovate[bot]
      - and: *CheckRuns
    actions:
      merge:
        method: squash
