name: GraphQL Inspector

on:
  push:
  pull_request:

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: Validate GraphQL API
          schema: 'main:schema.graphql'
          approve-label: breaking-change
